### ISSUE TITLE
Sort out various boundary problems

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#102]
Oh the horror, _the horror_! Can open - worms everywhere :(

![image](https://user-images.githubusercontent.com/6025893/32452009-42df125a-c310-11e7-97a4-8549a46ac383.png)

There are a variety of boundary problems we need to sort out, of various levels of severity.

Before I created the election ids for the All-up elections in May 2018, I checked that there hadn't been any completed boundary reviews completed since ~April this year. However, I have missed 2 important categories of changes that we should have taken into account before creating the IDs:

* There are some areas which had boundary changes before the local elections in 2017 which I assumed had been imported, but actually haven't. Example:

    Redbridge:
    * https://elections.democracyclub.org.uk/organisations/RDB/ (boundaries we hold, outdated)
    * http://www.lgbce.org.uk/current-reviews/greater-london/redbridge (boundary review 28th April 2017)
    * https://elections.democracyclub.org.uk/elections/local.redbridge.2018-05-03/ (election ids created against wrong boundaries)

    I guess, thinking about it, that @symroe only imported the reviewed boundaries that were actually relevant to elections happening in May 2017, not everything that had been reviewed since the last boundary line release. I hadn't realised this though :(

* There are some areas which currently have a boundary review in progress which is expected to be completed in time for the boundaries to apply to the elections in May 2018 but are still under review and where I've already created election ids. Example:

    Leeds:
    * https://elections.democracyclub.org.uk/organisations/LDS/ (boundaries we hold, current but due to be superseded)
    * http://www.lgbce.org.uk/current-reviews/yorkshire-and-the-humber/west-yorkshire/leeds (boundary review, still in progress)
    * https://elections.democracyclub.org.uk/elections/local.leeds.2018-05-03/ (election ids created against wrong boundaries)

Both of these cases are problematic because we've already created IDs against the wrong boundaries.

In the first case (e.g: Redbridge), I assume that the correct boundaries are now available in published sources so I assume that to account for these we can probably import the latest BoundaryLine or something rather than faffing with the Boundary Commission stuff (or is it better to establish the workflow that boundaries always come from the Boundary Commission first?). Then we'll need to delete the Election objects we've already created, re-create them and deal with the fact that they've already propagated to YNR, somehow. It was probably reasonable (in principle) to create the IDs, but we should have updated the boundaries first.

In the case of the boundary changes that are still under review (e.g: Leeds), the boundaries that will be used in May 2018 aren't even finalised yet (and may or may not be published by the OS before the elections). In these cases, my gut instinct is that we definitely shouldn't have created these election IDs because the relevant legislation defining the boundaries for the elections hasn't even been passed yet. I think we should just delete the IDs in these cases and re-create them once the boundaries are sorted.

The other 2 less serious categories of problem that exist are:

* In some areas, a boundary change has already happened and there is an election in May but we haven't already created any IDs yet because we don't know which wards have elections. Example:

    Harrogate:
    * https://elections.democracyclub.org.uk/organisations/HAG/ (boundaries we hold, outdated)
    * http://www.lgbce.org.uk/current-reviews/yorkshire-and-the-humber/north-yorkshire/harrogate (boundary review, 30 March 2017)

* There are some areas which currently have a boundary review in progress which is expected to be completed in time for the boundaries to apply to the elections in May 2018 but are still under review but where we haven't already created any IDs yet because we don't know which wards have elections. Example:

    Blackburn with Darwen:
    * https://elections.democracyclub.org.uk/organisations/BBD/ (boundaries we hold, current but due to be superseded)
    * http://www.lgbce.org.uk/current-reviews/north-west/lancashire/blackburn-and-darwen (boundary review, still in progress)

These cases are both easier to solve because we haven't created the IDs yet, so basically we just need to import the boundaries (by fair means or foul) **before** we create the IDs.

OK then, so those are the various categories of problems. Now on to the exhaustive lists of which areas exhibit each issue:

### 1 - (wrong) Elections already created, boundary change already happened:

* Redbridge
* Bexley
* Huntingdonshire
* South Cambridgeshire

Proposed fix:

* Import new boundaries (somehow)
* Delete and re-make the Election IDs
* Deal with the fact they've propagated to YNR (somehow)

### 2 - (wrong) Elections already created, boundary change going to happen but not finalised:

* Croydon
* Kingston-upon-Hull
* Leeds
* Newcastle-upon-Tyne
* Newcastle-under-Lyme
* South Lakeland

Proposed fix:

* Delete the Election IDs
* Deal with the fact they've propagated to YNR (somehow)
* Import new boundaries (once they're official) and then re-make the elections

### 3 - Elections not yet created, boundary change already happened:

* Harrogate

Proposed fix:

* Import new boundaries (somehow)
* Make election IDs when we know what elections are happening

### 4 - Elections not yet created, boundary change going to happen but not finalised:

* Blackburn with Darwen
* Preston

Proposed fix:

* Import new boundaries (somehow, once they're official)
* Make election IDs when we know what elections are happening

### 5 - Whatever has gone on here:

* Manchester: https://elections.democracyclub.org.uk/organisations/MAN/

Then there's also..

### 6 - Areas which have had a recent change or have an upcoming change which don't have an election scheduled for May:

(and hence we don't care about these _right now_ but will care about _at some point_)

Already happened:

* Chichester

Under review:

* Allerdale
* Ashford
* Babergh
* Bath & North East Somerset
* Bolsover
* Cheshire West & Chester
* Cornwall
* Dartford
* East Devon
* East Hampshire
* Forest of Dean
* Harborough
* Hertsmere
* Horsham
* King's Lynn and West Norfolk
* Mid Suffolk
* North Devon
* North East Derbyshire
* North Norfolk
* Nottingham
* Redcar and Cleveland
* Ribble Valley
* Richmondshire
* Rotherham
* Rutland
* Scarborough
* South Gloucestershire
* South Norfolk
* South Somerset
* Surrey Heath
* Taunton Deane
* Teignbridge
* Tendring
* Test Valley
* Tewkesbury
* Torbay
* Torridge
* West Berkshire
* Windsor and Maidenhead

Then, finally, the other thing this raises is how to avoid this happening again. Part of the issue is keeping better track of boundary changes and ECOs. Part of it is having better processes around when we create election ids (i.e: we shouldn't be creating ids when we know the boundaries that election will relate to haven't been formalised yet because the ECO hasn't been passed). It all needs some thought..

**Comment by chris48s** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LGBCE reviews](https://trello.com/c/dlncKpwS/1048-lgbce-reviews)

**Comment by chris48s** [comment]
Additionally, in fixing this, there are 3 cases we need to account for:

1a. The wards have the same names, but the (multi-)polygons they represent have changed. In that case, the ID strings are the same but just linked to different shapes

1b. The wards **should** have the same names, the (multi-)polygons they represent have changed but they don't **actually** have the same names because last bit of legislation said the ward name was "Miles Platting & Newton Heath" and the new bit says it is "Miles Platting and Newton Heath" (or whatevz). In this case, the ID string we've generated are incorrect, but we can probably fudge it..

2 The wards have got new names or wards have merged/split. In this case, the ID string we've generated are incorrect

**Comment by chris48s** [comment]
Another related job: set end dates on boundaries which we know are under review so we can't create more elections with the wrong boundaries.

This is a task we should do now but it is also something we should build in to the 'do boundaries properly'/boundary bot workflow as we establish it.

**Comment by jf1** [comment]
Nice to see this progress, however I'm not sure I agree with "we shouldn't be creating [EE election] ids when we know the boundaries that election will relate to haven't been formalised yet". I don't believe that approach is necessary.

Considering the points you made in 98 (which appear sound), and without knowledge of the intricacies of the data model(s) so apologies for that, would these issues be addressed by this scenario:
EE's elections data contains the LA and wards IDs (EE format, not GSS) and date,
EE's boundary data enables selection of the correct (date-tagged) boundary,
Fallback option if no boundary data is available for that area/date combination.

In the fallback scenario, c.dc could be operational (its users can still manually navigate to that election), although Who can't be (as AIUI postcode->ward lookup is a requirement). The latter could have another fallback of "We know elections are scheduled for [Organisation name] but can't yet confirm your [Division type] as new boundaries have been proposed but are not yet approved" (although that's unlikely to be seen apart from by testers as people are unlikely to visit Who before boundaries have been finalised).

This depends on your "Solution 2" (decoupling GSS codes and creating internal IDs that can be used independently from GSS IDs and also in advance of new GSS IDs being announced). Optionally EE's boundary data system could contain still-TBC new boundaries that don't yet have GSS IDs, however this is a policy (rather than technical) decision that depends on your view wrt: risk of having to re-import (revised) new boundaries vs reduced functionality of c.dc for early crowdsourcers.

For info, Manchester Labour party has agreed candidates (for all wards afaik) and printed and distributed materials to promote the candidates standing in at least one of the new wards (Piccadilly). Therefore we're now in a position where crowdsourcers might want to add data that EE/c.dc is not yet able to accept.

**Comment by symroe** [comment]
[quick reply for now]

Let's not confuse boundaries with wards. That is, you are right that we can make IDs before we have the boundaries, but we can't make IDs until we have the final ward list from the ECO. 

There are some areas up for election in May 2018 that haven't finished their consultation yet, so the ward names aren't final. If two wards are merged and we have imported them in to YNR, all sort of problems arise, especially if we have candidate data for some of them…

**Comment by chris48s** [comment]
Firstly, you deserve a medal for reading all of that - well done :medal_sports: 

Secondly, I think there are (at least) 2 cases we need to consider here:

One is where a boundary review is in progress and it is known how many wards the area will be divided into following the boundary review and what the names of them will be. In that case we could (in principle) safely create the divisions with a null or TBC geography to be attached later.

The second is where a boundary review is in progress and potentially the number of wards the area will be divided into following the boundary review and what the names of them will be is still subject to change/review. In that case we can't safely create the divisions.

At the moment we're still getting our heads around the boundary review/Electoral Change Order process and I have no idea how we can know this from the publicly available information (or whether we even can know this).

It is something we do need to think about as part of nailing down how we ingest data from the Boundary Commission and we are in very early stages of working this out.

**Comment by jf1** [comment]
All good :smile: 

I'd considered that but omitted to mention it as for case 2 I believe the only option is to wait.

For case 1 any decision to proceed should be based on the level of confidence in the new ward quantity and names, hopefully balanced with a desire to encourage crowd-sourcing, or perhaps more importantly to ensure c.dc isn't considered 'too slow' by keen crowd-sourcers (or party staff) who may forget or choose not to return.

It's not a binary situation and I don't know how you can quantify confidence in as-yet unpublished legislation. I'll try to get someone in Manchester to comment off the record. The signs are that other institutions are cracking on, expecting at least the number and names of wards to be as proposed by the review.

**Comment by chris48s** [comment]
> I don't know how you can quantify confidence in as-yet unpublished legislation

No, me either. One thing we need to find out more about is that a boundary review takes place in multiple stages. I think there are usually 'draft recommendations', 'final recommendations' and then another period between final recommendations being approved and actually becoming legislation. I'm unclear exactly how much wiggle room there is at each of those stages, and whether there are certain things that are constrained at each stage.

@symroe - one interesting thing to note re: our plans on this is that for Manchester specifically the [LGBCE website](http://www.lgbce.org.uk/current-reviews) references "The Manchester (Electoral Changes) Order 2017" and says "that **draft** Order has successfully passed through Parliament" but it is still listed under "Current Reviews" rather than "Recently Completed" so it may be that there is some category of reviews which I've categorised as in progress but we now know aren't subject to further changes even though the LGBCE site doesn't list them as "completed" yet.

**Comment by jf1** [comment]
> period between final recommendations being approved and actually becoming legislation.

This stage will always exist, and within it there'll be a period when all involved know that the legislation will (almost certainly) be passed/enacted/whatever, They need this knowledge in order to commit (resources) to getting everything in place so they're ready for when the legislation is in place. My efforts here are to encourage DC to proceed once this (perhaps hidden) official work has the go-ahead.

**Comment by chris48s** [comment]
At the moment we just aren't on top of the changes at all though (pre or post-legislation) - hence ending up in the mess describe in the first post where I've accidentally created elections against obsolete wards :(

Main thing to do is sort that out first.

In terms of the wider issue of how we deal with it moving forwards, I don't think I understand what can happen at the different stages of the review process clearly enough to have a stance on exactly what we should do when yet..

**Comment by chris48s** [comment]
Note: Some of the ones I've identified above as having "not finalised" boundary reviews may actually have a "made" ECO so those need checking because in that case they can shift categories.

**Comment by chris48s** [comment]
Update: I've now deleted the bad IDs we created for 

* Redbridge
* Bexley
* Huntingdonshire
* South Cambridgeshire
* Croydon
* Kingston-upon-Hull
* Leeds
* Newcastle-upon-Tyne
* Newcastle-under-Lyme
* South Lakeland

**Comment by chris48s** [comment]
Started tracking this in https://docs.google.com/spreadsheets/d/18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM/edit#gid=105385696

Given there are areas which:
* Have election in May 2018
* Have an ECO made after the Oct 2017 Boundary Line release
* Don't have shapes published by the Boundary Commission yet

I'm going to park this until we get a chance to follow this up with LGBCE.

**Comment by chris48s** [comment]
In lieu of a better place to be tracking this I'm going to note this here so we have some kind of record of what happened when:

December 19th 2017, ran: `python manage.py update_end_dates -u "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=1478559972"`

17th Jan 2018, ran: `python manage.py update_end_dates --overwrite -u "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=401759896"`

**Comment by chris48s** [comment]
..and again `python manage.py update_end_dates -u "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=737416808"`

**Comment by chris48s** [comment]
Right then... let's wrap this badboy up:

As noted in the above comments, following on from the work in #135 I ran

2017-12-18:
`python manage.py update_end_dates -u "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=626877429"`
2017-12-19:
`python manage.py update_end_dates -u "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=1478559972"`
2018-01-17:
`python manage.py update_end_dates --overwrite -u "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=401759896"`
2018-01-18:
`python manage.py update_end_dates -u "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=737416808"`

to set end dates.

Then following on from the work in #162 I ran 

2018-02-02:
`python manage.py import_divisionsets_from_csv "https://docs.google.com/spreadsheet/ccc?key=18X4wYGGmJNbL9xwN-ALXPQYDAed4PN1M9xC0YiKZ-TM&output=csv&gid=1833724937"`

to import names

and then following on from the work in #165 I ran 

2018-02-02:
```bash
python manage.py import_lgbce ALL "allerdale/The Allerdale (Electoral Changes) Order 2017/Allerdale_final_proposals.zip"
python manage.py import_lgbce CRY "croydon/London Borough of Croydon (Electoral Changes) Order 2017/Croydon_final_proposals.zip"
python manage.py import_lgbce HAO "harborough/The Harborough (Electoral Changes) Order 2017/Harborough_polygons.zip"
python manage.py import_lgbce KHL "kingston-upon-hull/The Kingston upon Hull (Electoral Changes) Order 2017/Hull_final_proposals.zip"
python manage.py import_lgbce NEC "newcastle-under-lyme/Newcastle-under-Lyme (Electoral Changes) Order 2017/NEWCASTLEUNDERLYME_final_proposals.shp.zip" -n "Ward_name"
python manage.py import_lgbce NNO "north-norfolk/The North Norfolk (Electoral Changes) Order 2017/NorthNorfolk_final_proposals.zip"
python manage.py import_lgbce TEN "tendring/The Tendring (Electoral Changes) Order 2017/Tendring_final_proposals.zip"
python manage.py import_lgbce TES "test-valley/The Test Valley (Electoral Changes) Order 2018/TestValley_final_proposals.zip"
python manage.py import_lgbce TEW "tewkesbury/The Tewkesbury (Electoral Changes) Order 2018/Tewkesbury_final_proposals.zip"
python manage.py import_lgbce HOR "horsham/Horsham (Electoral Changes) Order 2017/Horsham-fixed.zip"
python manage.py import_lgbce BBD "blackburn-and-darwen/The Blackburn with Darwen (Electoral Changes) Order 2017/Blackburn with Darwen.zip"
python manage.py import_lgbce BOS "bolsover/The Bolsover (Electoral Changes) Order 2017/Bolsover.zip" -n "wardname"
python manage.py import_lgbce NED "north-east-derbyshire/The North East Derbyshire (Electoral Changes) Order 2017/North East Derbyshire.zip" -n "wardname"
python manage.py import_lgbce RIB "ribble-valley/The Ribble Valley (Electoral Changes) Order 2017/Ribble Valley.zip" -n "ward_name"
python manage.py import_lgbce SLA "south-lakeland/The South Lakeland (Electoral Changes) Order 2017/South Lakeland.zip"
python manage.py import_lgbce HUN "huntingdonshire/The Huntingdonshire (Electoral Changes) Order 2017/Huntingdonshire.zip"
python manage.py import_lgbce SNO "south-norfolk/The South Norfolk (Electoral Changes) Order 2017/South Norfolk.zip"
python manage.py import_lgbce CHI "chichester/The Chichester (Electoral Changes) Order 2017/Chichester.zip"
python manage.py import_lgbce HAG "harrogate/The Harrogate (Electoral Changes) Order 2017/Harrogate.zip"
python manage.py import_lgbce LDS "leeds/The Leeds (Electoral Changes) Order 2017/Leeds.zip" -n "wardname"
python manage.py import_lgbce NET "newcastle-upon-tyne/The Newcastle upon Tyne (Electoral Changes) Order 2017/Newcastle upon Tyne.zip"
python manage.py import_lgbce SUR "surrey-heath/The Surrey Heath (Electoral Changes) Order 2017/Surrey Heath_fixed.zip"
python manage.py import_lgbce TOR "torridge/The Torridge (Electoral Changes) Order 2017/Torridge_fixed.zip"
python manage.py import_lgbce BEX "bexley/London Borough of Bexley (Electoral Changes) Order 2017/Bexley_fixed.zip"
python manage.py import_lgbce RDB "redbridge/The London Borough of Redbridge (Electoral Changes) Order 2017/Redbridge_fixed.zip"
python manage.py import_lgbce SCA "south-cambridgeshire/South Cambridgeshire (Electoral Changes) Order 2017/South Cambridgeshire_fixed.zip"
python manage.py import_lgbce TEI "teignbridge/The Teignbridge (Electoral Changes) Order 2017/Teignbridge.zip"
```

where we've got issues for specific areas, I've noted the data source and import command in the issue before closing it, but a lot of this backlog pre-dates boundary bot, so that only represents a subset of this backlog.

There are 4 areas which require additional work because something odd has happened (Manchester, Isles of Scilly, Hastings, Ashford) but I'll keep track of them elsewhere.

Obviously there is now rolling work to keep on top of this process moving forwards and prevent us from getting into this mess again, but each review will have its own issue in future (e.g: #173).

There is also some additional work to do on documenting this process and working out how to make what we're doing somehow reproducible which I will track in #100
