### ISSUE TITLE
ValueError creating election object for GLA Constituency

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#112]
```
from elections.utils import ElectionBuilder
x = ElectionBuilder('gla', '2017-01-01')
x.with_subtype('c')
ValueError: 'c' is not a valid subtype for election type 'Greater London assembly'
```

oh noes!!

**Comment by chris48s** [comment]
@symroe - the reason this is happening is because `ElectionBuilder` is expecting to be passed django objects not strings, so it is failing because `'c'` is not in `<QuerySet [<ElectionSubType: Constituencies (Greater London assembly)>, <ElectionSubType: Additional (Greater London assembly)>]>`. The 'correct' way to do the above would be to pass `with_subtype()` an `ElectionSubType` object, like this:

```
>>> from elections.utils import ElectionBuilder
>>> from elections.models import ElectionSubType
>>> from elections.models import ElectionType
>>> e = ElectionType.objects.filter(election_type='gla')
>>> s = ElectionSubType.objects.filter(election_type=e, election_subtype='c')
>>> x = ElectionBuilder('gla', '2017-01-01')
>>> x.with_subtype(s[0])
['gla.2017-01-01']
>>> 
```

(..and the same for orgs, divisions, etc with the respective django models). The `IdBuilder` object can just be passed simple strings.

If this is an error we're hitting somewhere in the wizard because we're trying to pass `ElectionBuilder` a string rather than an object, let me know where it is and I'll have a look. If you're just hitting it on the console then this is expected behaviour.

**Comment by symroe** [comment]
A possible new bug with this:

```python
>>> builder = ElectionBuilder('gla', '2017-06-08')
>>> builder.build_election_group()
ValueError: election_type gla must have a valid subtype before setting a division
```

**Comment by chris48s** [comment]
OK. These bugs are only on GLA, right.. NAW and SP are ok?

**Comment by symroe** [comment]
AFIK yes
