### ISSUE TITLE
FK from OrganisationDivision to OrganisationDivisionSet should be NOT NULL

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#113]
Currently `OrganisationDivision` has this:

```python
    divisionset = models.ForeignKey(
        OrganisationDivisionSet, related_name='divisions', null=True)
```
I can think of no cases where a division wouldn't have a divisionset. I think this was done to make the importing easier with the dance we have to do around guessing OrganisationDivisionSets from MaPit.

Is there any reason for it to have `null=True` in there?

**Comment by chris48s** [comment]
Is there a situation in the 'bootstrapping' code where we need to save a bunch of `OrganisationDivision` objects and then attach them to a set afterwards?

Do we always create an `OrganisationDivisionSet` and then save a bunch of `OrganisationDivision`s against that set?

**Comment by symroe** [comment]
I think we might be doing this, but if so I think we should move away from it – I can't actually think of a reason why we'd a) know a division exists and b) have no idea how it related to a divisionset at the point of creating it.

**Comment by chris48s** [comment]
Yeah - I think we're aligned on this:

From a theoretical perspective, there is no reason why this should validly be `null`.

From a practical perspective, naively applying the constraint might break some bootstrapping code (which we should probably fix as part of the process).

**Comment by symroe** [comment]
It broke the tests quite a lot too, but I've fixed that in a PR that's coming…
