### ISSUE TITLE
API enhancement: filter elections by organisation

### ISSUE THREAD

**Issue by GfxKai** [DemocracyClub/EveryElection#1151]
### Context
I'm building a data visualisation tool to show the latest local election results for all wards within a specified area.

### Issue
Currently, the most efficient way of finding the latest election for each local authority / ward is by calling the `/elections` endpoint with `group_type=organisation` (organisation level elections only) and `poll_open_date__gte=2017-01-01` (a bit more than 4 years to capture a full council term) to retrieve all organisation level elections. However, this returns ~1600 results, takes around 18s in total and loads a huge amount of unnecessary data.

### Proposed solution
It would be really useful to be able to filter the `/elections` response by `organisation.official_identifier` so that I can quickly and easily find the latest elections for each local authority. Since the election object contains the `organisation` relationship already, hopefully it's not a huge task!

### Additional information

It seems like the query I'm looking for already exists in some form, as it's visible at the bottom of each Organisation page under "Elections". See [Bristol](https://elections.democracyclub.org.uk/organisations/local-authority/BST/1996-04-01/) for example!
https://github.com/DemocracyClub/EveryElection/blob/19da682c2a1827d1c7017cf9a052237676dd0669/every_election/apps/organisations/views/public.py#L38-L54
https://github.com/DemocracyClub/EveryElection/blob/19da682c2a1827d1c7017cf9a052237676dd0669/every_election/apps/organisations/templates/organisations/organisation_detail.html#L67-L73

**Comment by michaeljcollinsuk** [comment]
Hi @GfxKai I've now merged and deployed a [PR](https://github.com/DemocracyClub/EveryElection/pull/1157) to make it easier to get all elections for a given organisation. It might be worth checking the comments on the PR from Chris for more context, but tl;dr - it wasn't as straightforward as adding the `official_identifier` as a filter on the Elections endpoint as these are not actually unique. 

So instead, I've added a `/elections/` endpoint to the Organisation viewset to return a list of all elections for an individual organisation e.g. https://elections.democracyclub.org.uk/api/organisations/local-authority/ADU/1974-04-01/elections/

In addition, I have added the `organisation_identifier`, `organisation_start_date`, and `organisation_type` as filters on the `/elections/` endpoint. So if preferred, you could get the same list of elections for an individual organisation by combining these filters e.g. https://elections.democracyclub.org.uk/api/elections/?organisation_type=local-authority&organisation_identifier=ADU&organisation_start_date=1974-04-01.

Hopefully these changes help you with your project!
