### ISSUE TITLE
Can't create Medway by-election

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/EveryElection#1162]
Creating `local.medway.strood-north.by.2021-08-26` throws an error - `local.medway.princes-park.by.2021-08-26` was created fine

![image](https://user-images.githubusercontent.com/10633357/126837405-47271403-f812-4254-8356-7b30606dd99e.png)
![image](https://user-images.githubusercontent.com/10633357/126837462-653b92b2-beee-40e4-99ab-67323e3b5dd4.png)

**Comment by sjorford** [comment]
Seems fixed now? I managed to create the election this morning before I saw this

**Comment by symroe** [comment]
The problem was basically causes by a cache in the ID creator — as it happens, the cache has invalidated, but the fix to the underlying problem hasn't been deployed yet.
