### ISSUE TITLE
Issue with the Liverpool election ID

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/EveryElection#12]
From fbrc again: 

>On last week's blog you were talking about groups of elections. I noticed the mayor ID for Liverpool's combined authority has the same format as last year's for Mayor of Liverpool City Council i.e. mayor.liverpool.{date} but they are two different people. Is this a problem?

This seems like a problem. In the EveryElection [spreadsheet](https://docs.google.com/spreadsheets/d/1eJMr8SRZTte55U_Bt4FvNpdZjdG3s9IywJNCX6G7zpE/edit#gid=0) (column I, row 19), it has mayor.liverpool-city-region.2017-05-04, which seems right. 

So I'm a bit confused as to what's happening. Nothing new there then!

**Comment by symroe** [comment]
Too many layers of democracy! I mistakenly thought that the Liverpool Mayor was of Liverpool, but it's the Liverpool combined authority. 

I've created a new organisation with a slug of `liverpool-city-ca`, so the ID is now `mayor.liverpool-city-ca.2017-05-04`
