### ISSUE TITLE
Completed boundary review for Allerdale

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#120]
Completed boundary review for Allerdale: http://www.lgbce.org.uk/current-reviews/north-west/cumbria/allerdale

**Comment by chris48s** [comment]
http://www.lgbce.org.uk/__data/assets/file/0005/33584/Allerdale_final_proposals.zip

**Comment by chris48s** [comment]
`python manage.py import_lgbce ALL "allerdale/The Allerdale (Electoral Changes) Order 2017/Allerdale_final_proposals.zip"`
