### ISSUE TITLE
Completed boundary review for Croydon

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#122]
Completed boundary review for Croydon: http://www.lgbce.org.uk/current-reviews/greater-london/croydon

**Comment by chris48s** [comment]
http://www.lgbce.org.uk/__data/assets/file/0004/34078/Croydon_final_proposals.zip

**Comment by chris48s** [comment]
`python manage.py import_lgbce CRY "croydon/London Borough of Croydon (Electoral Changes) Order 2017/Croydon_final_proposals.zip"`
