### ISSUE TITLE
Completed boundary review for Harborough

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#123]
Completed boundary review for Harborough: http://www.lgbce.org.uk/current-reviews/east-midlands/leicestershire/harborough

**Comment by chris48s** [comment]
http://www.lgbce.org.uk/__data/assets/file/0003/34086/Harborough_polygons.zip

**Comment by chris48s** [comment]
`python manage.py import_lgbce HAO "harborough/The Harborough (Electoral Changes) Order 2017/Harborough_polygons.zip"`
