### ISSUE TITLE
Completed boundary review for Horsham

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#124]
Completed boundary review for Horsham: http://www.lgbce.org.uk/current-reviews/south-east/west-sussex/horsham

**Comment by chris48s** [comment]
http://www.lgbce.org.uk/__data/assets/file/0007/33586/Horsham-Polygons.zip

**Comment by chris48s** [comment]
`python manage.py import_lgbce HOR "horsham/Horsham (Electoral Changes) Order 2017/Horsham-fixed.zip"`
