### ISSUE TITLE
Completed boundary review for Leeds

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#125]
Completed boundary review for Leeds: http://www.lgbce.org.uk/current-reviews/yorkshire-and-the-humber/west-yorkshire/leeds

**Comment by chris48s** [comment]
requires follow up with LGBCE

**Comment by chris48s** [comment]
https://lgbce-mirror.s3.amazonaws.com/leeds/The%20Leeds%20%28Electoral%20Changes%29%20Order%202017/Leeds.zip

`python manage.py import_lgbce LDS "leeds/The Leeds (Electoral Changes) Order 2017/Leeds.zip" -n "wardname"`
