### ISSUE TITLE
Completed boundary review for Newcastle-under-Lyme

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#127]
Completed boundary review for Newcastle-under-Lyme: http://www.lgbce.org.uk/current-reviews/west-midlands/staffs/newcastle-under-lyme

**Comment by chris48s** [comment]
http://www.lgbce.org.uk/__data/assets/file/0006/33594/NEWCASTLEUNDERLYME_final_proposals.shp.zip

**Comment by chris48s** [comment]
`python manage.py import_lgbce NEC "newcastle-under-lyme/Newcastle-under-Lyme (Electoral Changes) Order 2017/NEWCASTLEUNDERLYME_final_proposals.shp.zip" -n "Ward_name"`
