### ISSUE TITLE
Completed boundary review for South Norfolk

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#129]
Completed boundary review for South Norfolk: http://www.lgbce.org.uk/current-reviews/eastern/norfolk/south-norfolk

**Comment by chris48s** [comment]
requires follow up with LGBCE

**Comment by chris48s** [comment]
https://lgbce-mirror.s3.amazonaws.com/south-norfolk/The%20South%20Norfolk%20%28Electoral%20Changes%29%20Order%202017/South%20Norfolk.zip

`python manage.py import_lgbce SNO "south-norfolk/The South Norfolk (Electoral Changes) Order 2017/South Norfolk.zip"`
