### ISSUE TITLE
Completed boundary review for Teignbridge

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#130]
Completed boundary review for Teignbridge: http://www.lgbce.org.uk/current-reviews/south-west/devon/teignbridge

**Comment by chris48s** [comment]
requires follow up with LGBCE

**Comment by chris48s** [comment]
https://lgbce-mirror.s3.amazonaws.com/teignbridge/The%20Teignbridge%20%28Electoral%20Changes%29%20Order%202017/Teignbridge.zip

`python manage.py import_lgbce TEI "teignbridge/The Teignbridge (Electoral Changes) Order 2017/Teignbridge.zip"`
