### ISSUE TITLE
Completed boundary review for Tendring

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#131]
Completed boundary review for Tendring: http://www.lgbce.org.uk/current-reviews/eastern/essex/tendring

**Comment by chris48s** [comment]
http://www.lgbce.org.uk/__data/assets/file/0018/34074/Tendring_final_proposals.zip

**Comment by chris48s** [comment]
`python manage.py import_lgbce TEN "tendring/The Tendring (Electoral Changes) Order 2017/Tendring_final_proposals.zip"`
