### ISSUE TITLE
Completed boundary review for Torridge

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#132]
Completed boundary review for Torridge: http://www.lgbce.org.uk/current-reviews/south-west/devon/torridge

**Comment by chris48s** [comment]
requires follow up with LGBCE

**Comment by chris48s** [comment]
https://lgbce-mirror.s3.amazonaws.com/torridge/The%20Torridge%20%28Electoral%20Changes%29%20Order%202017/Torridge_fixed.zip

`python manage.py import_lgbce TOR "torridge/The Torridge (Electoral Changes) Order 2017/Torridge_fixed.zip"`
