### ISSUE TITLE
Upgrade python/django/etc versions

### ISSUE THREAD

**Issue by GeoWill** [DemocracyClub/EveryElection#1349]
It would be good to upgrade (post elections)
Python and Django versions - there are various libs that are blocked on this and it will probably be a complimentary piece of work to #1283. 
I'm creating this issue to keep track of other libraries that are blocked by this.

**Comment by GeoWill** [comment]
- psycopg2-binary
- django-cors-headers
- importlib-metadata

**Comment by VirginiaDooley** [comment]
Reopening until we reach Python 3.10 and Django 4.1.2

**Comment by symroe** [comment]
I think this is done now
