### ISSUE TITLE
Prevent overlapping start and end dates

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#136]
Where we've got multiple org/div sets for an org, the start/end dates shouldn't be able to overlap

i.e: it shouldn't be possible for the start date of the next generation to be before the end date of the previous generation

It would be helpful to enforce this as a DB constraint. It appears that it is possible to do this in postgres:
https://stackoverflow.com/questions/10616099/postgres-date-overlapping-constraint
but we won't be able to do it via Django's ORM: we'll have to add it as a custom migration.

Also we'll need to identify any cases where this error already exists and fix them before we can safely apply this migration.

When we do #15 we should apply the same rule there too.

**Comment by chris48s** [comment]
Also it should be invalid for 2 division sets relating to the same org to both have a `NULL` `end_date`

**Comment by symroe** [comment]
Presumably this one can be added with `unique_together=(organisation, end_date)`?
