### ISSUE TITLE
Completed boundary review for Ribble Valley

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#142]
Completed boundary review for Ribble Valley: http://www.lgbce.org.uk/current-reviews/north-west/lancashire/ribble-valley

**Comment by chris48s** [comment]
requires follow up with LGBCE

**Comment by chris48s** [comment]
https://lgbce-mirror.s3.amazonaws.com/ribble-valley/The%20Ribble%20Valley%20%28Electoral%20Changes%29%20Order%202017/Ribble%20Valley.zip

`python manage.py import_lgbce RIB "ribble-valley/The Ribble Valley (Electoral Changes) Order 2017/Ribble Valley.zip" -n "ward_name"`
