### ISSUE TITLE
Completed boundary review for Surrey Heath

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#143]
Completed boundary review for Surrey Heath: http://www.lgbce.org.uk/current-reviews/south-east/surrey/surrey-heath

**Comment by chris48s** [comment]
requires follow up with LGBCE

**Comment by chris48s** [comment]
https://lgbce-mirror.s3.amazonaws.com/surrey-heath/The%20Surrey%20Heath%20%28Electoral%20Changes%29%20Order%202017/Surrey%20Heath_fixed.zip

`python manage.py import_lgbce SUR "surrey-heath/The Surrey Heath (Electoral Changes) Order 2017/Surrey Heath_fixed.zip"`
