### ISSUE TITLE
Completed boundary review for North East Derbyshire

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#144]
Completed boundary review for North East Derbyshire: http://www.lgbce.org.uk/current-reviews/east-midlands/derbyshire/north-east-derbyshire

**Comment by chris48s** [comment]
requires follow up with LGBCE

**Comment by chris48s** [comment]
https://lgbce-mirror.s3.amazonaws.com/north-east-derbyshire/The%20North%20East%20Derbyshire%20%28Electoral%20Changes%29%20Order%202017/North%20East%20Derbyshire.zip

`python manage.py import_lgbce NED "north-east-derbyshire/The North East Derbyshire (Electoral Changes) Order 2017/North East Derbyshire.zip" -n "wardname"`
