### ISSUE TITLE
Completed boundary review for Tewkesbury

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#159]
Completed boundary review for Tewkesbury: http://www.lgbce.org.uk/current-reviews/south-west/gloucestershire/tewkesbury

**Comment by chris48s** [comment]
http://www.lgbce.org.uk/__data/assets/file/0005/35906/Tewkesbury_final_proposals.zip

**Comment by chris48s** [comment]
`python manage.py import_lgbce TEW "tewkesbury/The Tewkesbury (Electoral Changes) Order 2018/Tewkesbury_final_proposals.zip"`
