### ISSUE TITLE
"Mark all as contested" button

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#1725]
Previously, on the ID creator page that lists the divisions we had a button at the top of the page that said "mark all as contested". This was useful for all-up elections to save us having to click "contested" on each division.

@VirginiaDooley can you take a look at this? The old JS code will need updating, but it basically involves adding a button (using JS) and, when clicked, checking all "contested" radio buttons.

This didn't make it through the design system change. The old code is here: https://github.com/DemocracyClub/EveryElection/blob/344d58ecffae3e0dffddf57ebae6d9b4fb1e7977/every_election/apps/elections/templates/id_creator/election_organisation_division.html#L21

**Comment by pmk01** [comment]
Can I have my button back please, my finger hurts. 😥
