### ISSUE TITLE
Store if a given election requires ID, and if so what the requirements are

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#1729]
Some UK elections require ID in order to vote in person.

Before 2023 all of these elections were in Northern Ireland. This meant the only logic needed was to check the country the election was being held in and show text accordingly.

After 2023 the situation gets tricky.

All English elections will require ID (but this is phasing in, with general election law being activated later this year, so a parliamentary by-election now wouldn't require ID).

Welsh-run elections aren't going to need ID, but PCC and parliamentary elections in Wales are. Same for Scotland.

This means that EE should store, per ballot, if the election is going to require ID or not. 

The ID requirements might change over time or per ballot as well, so we should find a way to list the forms of ID (or at least a link to a page /object that knows the requirements).

**Comment by symroe** [comment]
Of course we can get away without doing this for May 23 as _all_ elections taking place on that day will need ID.

Or, the list of elections that don't (for example a parliamentary by-election on the same day) would be short and we could exclude them in the template layer.

**Comment by symroe** [comment]
There is an added bit of complexity here:

It's possible for someone to have two ballots: one that requires ID and one that doesn't. We need to tell people they need to bring ID if _any_ of the ballots require it.

**Comment by Bekabyx** [comment]
> Welsh-run elections aren't going to need ID, but PCC and parliamentary elections in Wales are. Same for Scotland.

Scotland PCC isn't on the EC's list of ID-requiring polls, but presumably only because Scotland doesn't actually _have_ PCCs. I'm sure this is already general knowledge but just adding the comment for clarity in these very confusing times 🤣
