### ISSUE TITLE
Be trailing-slash agnostic

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#187]
This is probably (hopefully) an easy fix

https://elections.democracyclub.org.uk/reference_definition works but
https://elections.democracyclub.org.uk/reference_definition/ 404s

https://elections.democracyclub.org.uk/elections works but
https://elections.democracyclub.org.uk/elections/ 404s

etc

We should be set up so that both version work, like this:

https://wheredoivote.co.uk/privacy
https://wheredoivote.co.uk/privacy/

**Comment by symroe** [comment]
I think The Django Way is to:

1. Always add a trailing slash to URL configs
2. Make sure [`APPEND_SLASH`](https://docs.djangoproject.com/en/dev/ref/settings/#append-slash) is `True`

This will issue a HTTP redirect from `https://wheredoivote.co.uk/privacy` to `https://wheredoivote.co.uk/privacy/`.

`django_extensions` provides a `show_urls` management command that might help:

```
py manage.py show_urls -f table | egrep -v "\/[ ]+\|"
URL                                                    | Module                                          | Name                                          | Decorator
-------------------------------------------------------+-------------------------------------------------+-----------------------------------------------+-
/election_types                                        | elections.views.general.ElectionTypesView       | election_types_view                           | 
/elections                                             | elections.views.general.AllElectionsView        | elections_view                                | 
/reference_definition                                  | elections.views.general.ReferenceDefinitionView | reference_definition_view                     | 
/static/<path>                                         | django.views.static.serve                       |                                               | 
```

Maybe we could add this as a check in CI in future?
