### ISSUE TITLE
Support JSONP in API

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#198]
Someone has asked for it and it's generally handy if you're doing JavaScript stuff. Almost no downsides to supporting it.

**Comment by samsmith** [comment]
the candidates_for_postcode API already supports it, but others do not. Turning it on everywhere would indeed be useful.

**Comment by chris48s** [comment]
At the same time, we should also enable CORS on the API which is also not enabled by default in DRF and makes the data more difficult to use client-side
