### ISSUE TITLE
An upcoming UK Parl by-election in West Tyrone.

### ISSUE THREAD

**Issue by BobHarper1** [DemocracyClub/EveryElection#211]
There is no confirmation yet, but it is expected to occur in 2018.

A ridiculous background story to the reasons for this [here](https://en.wikipedia.org/wiki/West_Tyrone_by-election,_2018)

**Comment by chris48s** [comment]
Cheers - its on our radar

**Comment by BobHarper1** [comment]
Now confirmed as 3 May http://www.bbc.co.uk/news/uk-northern-ireland-43601329

**Comment by chris48s** [comment]
sorted - thanks :)
https://elections.democracyclub.org.uk/elections/parl.2018-05-03/
