### ISSUE TITLE
EE says Doncaster does not have elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#23]
https://elections.democracyclub.org.uk/api/elections.json?postcode=DN84HX&future=1
https://elections.democracyclub.org.uk/elections/local.doncaster.2017-05-04/

At the moment we're incorrectly telling users on WDIV that they have no upcoming elections :(
https://wheredoivote.co.uk/postcode/DN84HX/

I'm _fairly_ sure this did work when I was writing Doncaster's import script..

**Comment by symroe** [comment]
See #24 – this should be fixed now after running `add_geography_to_elections`, but we should attach them when creating new IDs

**Comment by chris48s** [comment]
woo!
https://wheredoivote.co.uk/postcode/DN84HX/
..you've fixed at least one more thing than I've managed today
