### ISSUE TITLE
Can't edit an election and leave voter ID blank

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/EveryElection#2328]
'No' isn't an option in the voter ID dropdown. If we want to edit an election which isn't affected by voter ID, we can't.

![Screenshot 2024-11-28 124054](https://github.com/user-attachments/assets/9af1fe1b-cd2e-4390-a26d-166813872811)

**Comment by chris48s** [comment]
I probably broke this in https://github.com/DemocracyClub/EveryElection/pull/2313/commits/d26def82dbe89d5e7498ec0c3f2cde8cde010755
Adding to mop-up ticket https://app.asana.com/0/1204880927741389/1208865695360845/f
