### ISSUE TITLE
Assign geographies when adding a new election

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#24]
See https://github.com/DemocracyClub/yournextrepresentative/issues/87

**Comment by jf1** [comment]
Nice prompt fix, thanks - time to close this issue?

**Comment by symroe** [comment]
Nope, this is the root issue that caused your issue in the first place! :)

**Comment by jf1** [comment]
Ahh, so you manually fixed existing DC elections but it's still an issue in EE's code? Thanks all the same :)

**Comment by jf1** [comment]
You may wish to flag up that http://2017wards.mysociety.org/postcode/M145JB doesn't list the two by-elections
