### ISSUE TITLE
Better election titles for Mayoral elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#264]
(and maybe some other types)

see https://github.com/DemocracyClub/WhoCanIVoteFor/issues/265#issuecomment-383550005

**Comment by chris48s** [comment]
This problem also affects local councillor elections for wards in areas with a directly elected mayor: https://elections.democracyclub.org.uk/elections/local.salford.2018-09-27/

Maybe this is an issue when there are multiple election type or elected role objects associated with an organisation?

**Comment by symroe** [comment]
One thing that would help is for all the `mayor` names to be in the same format. 

This means editing some old ones to improve them, for example https://elections.democracyclub.org.uk/elections/mayor.hackney.2018-05-03/ could be more like https://elections.democracyclub.org.uk/elections/mayor.bedford.2019-05-02/.
