### ISSUE TITLE
Support 'current' elections

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#3]
We will want to have some idea of what elections are 'current', in a political sense.

Normally elections will be current for about 6 months before they happen, or, in the case of a by- or snap election from the time they are announced. They will remind 'current' for some time after the election, we can assume about a couple of months.

Each election will vary, to I suggest we have `current_from` and `current_to` fields that are pre-populated with safe defaults when the election is created. These dates can then be edited in the admin interface if needs be.

We can expose these values in the API, but also provide a filter and boolean `is_current`. This will help when consuming the API in cases where all historic elections aren't needed (like updating YNR).

**Comment by symroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support 'current' elections](https://trello.com/c/G1SiKZCZ/880-support-current-elections)

**Comment by JoeMitchell** [comment]
So, for example, 'current' would determine whether it shows up on WCIVF? 

On the timing: 
> Normally elections will be current for about 6 months before they happen...

Candidates get selected welllll more in advance than that. Potentially 18months+ (perhaps even years?)... does that mean the default 'current' should be bigger? 

And laaastly in my series of unhelpful questions, how would `current` compare with `~official` as a potential tag? That is, the period from when a notice of election has been published by a council, to 10pm election day...

**Comment by symroe** [comment]
> 'current' would determine whether it shows up on WCIVF

Right, this is the best way to think about it: as a status for our other sites to listen in to. Will we want to crowd source candidates more than 6 months before an election? Maybe! bit maybe not 18 months before?

> how would current compare with ~official as a potential tag?

So I want to support uploading Notice of Polls and exposing them in the API. When we do that we'll be able to figure out if there is an official notice – but that's not quite the same as a status is it? Do you think we should have a status field that we can update as the election progresses from speculation (in the case of an unscheduled election) to reality?

**Comment by JoeMitchell** [comment]
Dunno on timing really — as soon as we have a source for X person will stand in Y scheduled election, shouldn't we be able to capture that data somewhere? I recognise that for voters it's not useful, but maybe for local campaigners / local journalists it's useful...

On the un/official thing, I thiiink it probably doesn't matter. All I'd want is a note on WCIVF saying "This list is (not) final, as the SOPN has (not) been published."

**Comment by symroe** [comment]
So maybe the threshold for _WCIVF_ is that we have the _complete_ set of candidates. That way we're being most helpful to the voter, and not getting in to hot water about equal prominence etc.

Complete here is defined by locking an area on YNR. You're right that we should have all elections who have candidates selected in YNR.

**Comment by chris48s** [comment]
I'm going to close this on the basis that

https://github.com/DemocracyClub/EveryElection/blob/70e7c68e9fc6635ba178d09aa0494842c1309885/every_election/apps/elections/managers.py#L21-L32

exists. If further discussion is useful, re-open
