### ISSUE TITLE
Add election_status to EE data model

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/EveryElection#33]
The [2017-05-04 by-election for Manchester, Gorton](https://elections.democracyclub.org.uk/elections/parl.manchester-gorton.2017-05-04/) should be marked in EE as canceled, and EE could benefit from being able to assign this and other status values to any election. Example values below.

election_status:
Expected
Announced
Cancelled
Completed - or this could be: Polls Closed; Result Announced

If a changelog can accept a source then for the above example it would be: http://www.manchester.gov.uk/download/downloads/id/24869/notice_of_cancellation_of_manchester_gorton_parliamentary_by_election.pdf

**Comment by chris48s** [comment]
Another example of this:

Dacorum council recently scheduled an election for 1st March
https://notice-of-election.s3.amazonaws.com/local.dacorum.northchurch.by.2018-03-01/notice-of-election---borough-councillor-for-northchurch-ward.pdfsfvrsn2
and then rescheduled it for the 8th
https://notice-of-election.s3.amazonaws.com/local.dacorum.2018-03-08/notice-of-election---borough-08-03-18.pdf

a cancelled flag/status would definitely be useful

**Comment by chris48s** [comment]
also https://www.wigantoday.net/news/court-drama-as-bryn-by-election-ruled-not-lawful-and-scrapped-1-9028544

**Comment by chris48s** [comment]
https://assets.ctfassets.net/ii3xdrqc6nfw/2xxUNLHOYU0KaqiiIAeMCg/7e5e7777838ef8abf9c091144f017d5c/Notice_of_cancelled_election.pdf

**Comment by chris48s** [comment]
couple more example of this:

https://www.cherwell.gov.uk/download/downloads/id/7760/bicester-west-notice-of-countermanded-poll.pdf

http://tamworth.gov.uk/sites/default/files/councillors_docs/Notice-Of-Countermanded-Election-Glascote-Ward.pdf

**Comment by chris48s** [comment]
It would be useful to be able to link an election with a 'rescheduled' status to another record. i.e: if we set `local.tamworth.glascote.2018-05-03` to postponed, we could then create a FK to `local.tamworth.glascote.2018-05-25`, allowing us to say something more useful in WhoCIVF/WhereDIV than "we don't know of any upcoming elections"

**Comment by chris48s** [comment]
Done in https://github.com/DemocracyClub/EveryElection/pull/426
