### ISSUE TITLE
Consolidate OrganisationDivision.official_identifier and OrganisationDivision.geography_curie

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#348]
Merge these into one concept.

Should we also split the remaining consolidated field into `code_type` and `code`? My concern is that `WHERE LEFT(od.official_identifier,4) == 'gss:'` etc may not scale well as this table gets big (which it probably will).

**Comment by symroe** [comment]
I don't have strong opinions about merging the fields, but I don't think performance is a factor for the size of table we're talking about, even after a few years of operation.

Firstly, `LEFT` queries work nicely with B-Tree indexes anyway, and second, if it ever did become a problem (how often do we filter on `official_identifier[:4]` anyway?) we can add a [Trigram index](https://www.postgresql.org/docs/current/static/pgtrgm.html#id-1.11.7.41.7) to the field.

This isn't an argument for or against splitting it at all, just pointing out that _performance_ shouldn't be a factor in deciding.

**Comment by chris48s** [comment]
Useful points

> how often do we filter on `official_identifier[:4]` anyway?

Well the reason I had that in mind is because I'm currently writing a bunch of code that does that :D

I suppose the most important consideration is compatibility/interoperability. If changing this has a knock-on effect on YNR/other data consumers, I'm inclined to leave it as-is.

**Comment by chris48s** [comment]
Did this in #353
Leaving the code format as `gss:code`
