### ISSUE TITLE
Back port elections we've previously covered on YNR

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#355]
YNR covered some elections before EE was the source of them. Some of these elections existed before our election IDs too.

When I added `ballot_paper_ids` in to YNR (currently not exposed in most places) I added a temporary ID for all elections that hadn't come from EE. 

There are 8,068 `PostExtraElection` objects with these IDs.

This breaks down to these dates:

|Date|PEE Count|
|----|----:|
|2010-05-06|650|
|2015-05-07|650|
|2016-05-05|2390|
|2017-02-23|2|
|2017-03-02|18|
|2017-03-23|25|
|2017-05-04|3517|
|2017-05-11|1|
|2017-06-08|685|
|2017-06-29|2|
|2017-07-20|9|
|2017-07-27|3|
|2017-08-03|6|
|2017-08-17|4|
|2017-08-29|1|
|2017-08-31|1|
|2017-09-07|14|
|2017-09-11|1|
|2017-09-12|2|
|2017-09-14|3|
|2017-09-21|3|
|2017-09-28|12|
|2017-10-05|8|
|2017-10-12|8|
|2017-10-19|9|
|2017-10-26|6|
|2017-11-02|6|
|2017-11-09|5|
|2017-11-14|1|
|2017-11-16|10|
|2017-11-23|10|
|2017-11-30|4|
|2017-12-07|2|

As a first step, let's work out for how many of these we have division sets that cover the election date. For those, we should be able to just create the IDs and match them up to the YNR IDs (YNR has some form of ID for most of them, apart form the ones that had boundary changes before the election).

Once we know what the work looks like we can start splitting it up in to backporting boundaries/divisionsets we don't have in EE vs just creating the IDs.

I don't think we need boundaries as a high priority: we currently offer no public facing way to look up historic elections by postcode.

**Comment by chris48s** [comment]
Well it looks like 2010 and 2015 were general elections. We have a `DivisionSet` for parliament dated `2010-05-06`, so that looks like we should be good..

For 2016 onwards, for most organisations we have a `DivisionSet` object with a start date before those election dates. There are 21 organisations where we've got a `DivisionSet` where the start date is `2016-04-13`. I'm not sure what the significance of that date is (seems too early for a May BoundaryLine release), but its probably worth checking if any of those `2016-05-05` elections are for any of the following organisations:

Bristol City Council
Cherwell District Council
City of Lincoln Council
Colchester Borough Council
Craven District Council
Elmbridge Borough Council
Exeter City Council
Gloucester City Council
Knowsley Metropolitan Borough Council
Peterborough City Council
Rochford District Council
Scottish Parliament
Sheffield City Council
Stroud District Council
Warrington Borough Council
Watford Borough Council
Welsh assembly
Welwyn Hatfield Borough Council
West Oxfordshire District Council
Winchester City Council
Woking Borough Council

**Comment by symroe** [comment]
`2016-04-13` is the generation start date for the May 2016 Boundary-Line ([Generation 28](https://mapit.mysociety.org/generations)).

**Comment by symroe** [comment]
These are all the organisations for the `2016-05-05` elections:

```
adur
amber-valley
barnet
barnsley
barrow
basildon
basingstoke-and-deane
birmingham
blackburn-with-darwen
bolton
bradford
braintree
breckland
brent
brentwood
bridgend
bristol
broxbourne
burnley
bury
calderdale
cambridge
cambridgeshire
cannock-chase
canterbury
carlisle
castle-point
cheltenham
cherwell
chorley
colchester
coventry
craven
crawley
croydon
daventry
derby
doncaster
dudley
east-hampshire
east-riding-of-yorkshire
east-sussex
eastleigh
elmbridge
epping-forest
exeter
fareham
forest-heath
gateshead
gloucester
gloucestershire
gosport
great-yarmouth
greenwich
guildford
hackney
halton
hampshire
harlow
harrogate
hart
hartlepool
hastings
havant
havering
huntingdonshire
hyndburn
ipswich
kensington-and-chelsea
kingston-upon-hull
kirklees
knowsley
lancashire
lancaster
leeds
lincoln
liverpool
london
maidstone
manchester
melton
merton
middlesbrough
milton-keynes
mole-valley
newcastle-under-lyme
newcastle-upon-tyne
north-dorset
north-east-lincolnshire
north-hertfordshire
north-tyneside
norwich
nuneaton-and-bedworth
oldham
oxford
pendle
peterborough
plymouth
portsmouth
preston
reading
redbridge
redditch
reigate-and-banstead
rochdale
rochford
rossendale
rotherham
rugby
runnymede
rushmoor
salford
sandwell
sefton
sheffield
slough
solihull
south-buckinghamshire
south-bucks
south-cambridgeshire
south-kestevan
south-lakeland
south-ribble
south-tyneside
southampton
southwark
spelthorne
st-albans
st-edmondsbury
st-edmundsbury
st-helens
staffordshire
stevenage
stockport
stroud
suffolk
sunderland
surrey
swansea
swindon
tameside
tamworth
tandridge
tendring
three-rivers
thurrock
torbay
torquay
trafford
tunbridge-wells
wakefield
walsall
warrington
watford
waveney
welwyn-hatfield
west-lancashire
west-oxfordshire
westminster
weymouth-and-portland
wigan
wiltshire
winchester
wirral
woking
wokingham
wolverhampton
worcester
worthing
wyre-forest
```

**Comment by chris48s** [comment]
> `2016-04-13` is the generation start date for the May 2016 Boundary-Line ([Generation 28](https://mapit.mysociety.org/generations)).

..which is odd, seeing as its the *May* 2016 BoundaryLine release, right? I guess Maybe OS brought forward the May release in 2016 as well?

**Comment by symroe** [comment]
Yeah, they did one of those special forward dated downloads in 2016. I guess it wasn't a full BoundaryLine, but it was from OS and contained all the same data.

**Comment by chris48s** [comment]
so I guess the upshot of that is we should have the necessary gubbins to create ids for all those elections :)

**Comment by symroe** [comment]
THIS IS UNEXPECTED!
