### ISSUE TITLE
Add a way to specify if a local election is all-up or not

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#369]
In the wizard, when we are creating a local election it would be useful to be able to specify this. That would help us to be able to set useful values for `seats_contested` at creation time.

https://github.com/DemocracyClub/EveryElection/blob/88866bff99c2a52a9a3a63db653c7cf580f5ddaa/every_election/apps/elections/utils.py#L152-L164

**Comment by GeoWill** [comment]
This might be a useful feature for by elections too.

**Comment by chris48s** [comment]
As well as thinking of this as a binary "all up/not all up", it might be more helpful to express this as "pick a number between one and seats_total", but make it really easy to select 1 or seats_total for everything

**Comment by pmk01** [comment]
Closed via: https://github.com/DemocracyClub/EveryElection/issues/1406
