### ISSUE TITLE
Consistently put (or don't) the year in election names

### ISSUE THREAD

**Issue by tfgg** [DemocracyClub/EveryElection#43]
Currently the year is in some election names but not others. For examples see the election list here:

https://whocanivotefor.co.uk/elections/

To make designing user interfaces more uniform, names should either include the year or not. In my opinion they shouldn't, as the designer can always show the election_date.year.

**Comment by symroe** [comment]
TODO: produce a list of `ballot paper id, election name` as a CSV we can put in a Google doc and add fixed names to. Should think about the context of how we use the election names.

**Comment by pmk01** [comment]
Sort of related: https://github.com/DemocracyClub/yournextrepresentative/issues/67

**Comment by pmk01** [comment]
Dates removed from all election titles.
