### ISSUE TITLE
Can't create 2016 GLA elections

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#465]
1. Date: 2016-05-05
1. Select Regions or constituencies (both are broken)
1. ![screenshot 2018-12-19 17 52 51](https://user-images.githubusercontent.com/242329/50238330-0c31ce80-03b7-11e9-8285-fab4354559da.png)

**Comment by chris48s** [comment]
I've fixed this for constituencies. This was another one where the `division_election_sub_type` wasn't set for some reason. I've set all the constituencies to `c` and gone through all the divisions for organisations that use Additional Member System to make sure everything has got a subtype set on it (some of the pre-2016 Welsh Assembly ones also didn't have this).

Unlike NAW and Scottish Parliament, The GLA implementation of AMS does not use "regions". The 2 types are "constituencies" and "additional". I _think_ based on looking at [the spec](https://elections.democracyclub.org.uk/reference_definition/) its correct to just create `gla.a.date` (which you _can_ create with no divisions), but lets review that assumption tomorrow.
