### ISSUE TITLE
Add "source" field for elections

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#5]
We should track the sources of election IDs somehow.

The main thing to think about is how to add this to the ID creator form.

**Comment by symroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add "source" field for elections](https://trello.com/c/mJU9bRug/883-add-source-field-for-elections)

**Comment by symroe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add "source" field for elections](https://trello.com/c/mJU9bRug/883-add-source-field-for-elections)

**Comment by chris48s** [comment]
Other suggestions:

1. Source should be an actual notice of elections document. Validate that source field contains `.gov.uk`?
2. Back up the source document on creation in case it disappears
