### ISSUE TITLE
Can't create PCC elections

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#546]
Trying to create https://mobile.twitter.com/NorthumbriaPCC/status/1136936693746061313

Gives this

![image (1)](https://user-images.githubusercontent.com/242329/59194746-e923f280-8b81-11e9-8c6a-5c3ed72e451a.png)

(Via @sjorford)

**Comment by sjorford** [comment]
Actually, clicking __Submit__ does offer to create `pcc.2019-07-18` and `pcc.northumbria.2019-07-18` - not sure whether those are the right IDs though (I assume they should have `by` in there somewhere)

**Comment by chris48s** [comment]
Either way, its not doing exactly what its supposed to. I've got a couple of ideas what might be wrong. I'm taking tomorrow off, but I'll have a look at this on Friday or Monday.

/remind @chris48s ping on 2019-06-14

**Comment by chris48s** [comment]
https://elections.democracyclub.org.uk/elections/pcc.northumbria.by.2019-07-18/ now exists
