### ISSUE TITLE
Completed boundary review for Isle of Wight

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/EveryElection#636]
Completed boundary review for Isle of Wight: http://www.lgbce.org.uk/all-reviews/south-east/isle-of-wight/isle-of-wight

**Comment by GeoWill** [comment]
NB did:
`ogrinfo Isle_of_Wight_F_Division_polys.shp -dialect sql -sql "alter table Isle_of_Wight_F_Division_polys add column Name text"`
`ogrinfo Isle_of_Wight_F_Division_polys.shp -dialect SQLite -sql "update Isle_of_Wight_F_Division_polys set name=replace(DivisionNa,' ED','')"`
to get rid of trailing ' ED' on division names
