### ISSUE TITLE
Pull from new Wales register

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#69]
The register for Wales is no longer called "local-authority-wls". It's now "principal-local-authority".

We should update the importers to reflect this. 

This is mainly interesting because they've updated "Rhondda Cynon Taff" to be spelt "Rhondda Cynon Taf" (one F): https://github.com/openregister/local-authority-data/pull/35/files

**Comment by chris48s** [comment]
Isn't this already done in 0812015

**Comment by symroe** [comment]
Oh, I changed the URL, ace. In that case we need to re-run the importer to pull in the name change.

**Comment by chris48s** [comment]
This got done: https://elections.democracyclub.org.uk/organisations/RCT/
