### ISSUE TITLE
Moderate elections

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#79]
* Add authentication/login
* Election IDs created by admin users are automatically approved
* Anonymous users can still create election ids, but ids created by anonymous users are submitted for moderation/approval. Once approved by a moderator they can be synced through to YNR etc

**Comment by symroe** [comment]
> Add authentication/login

I reckon this could just be via the build in django admin for the time being, with us giving accounts to people we know. The number of people likely to ever use this site is a very manageable number to manually add, I expect.

**Comment by chris48s** [comment]
Presumably we can pick up from `request.user` whether someone is logged into `/admin` in the wizard?
If so, yeah - that sounds like a good way to tackle it

**Comment by chris48s** [comment]
closed in #451
