### ISSUE TITLE
More human election date picker?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/EveryElection#8]
![__democracy_club_elections_](https://cloud.githubusercontent.com/assets/8096305/22157819/3a4d24ce-df31-11e6-924b-4f63caf8ef36.jpg)

Obvs it gets recorded as a number, but I wonder if a user could choose from a list of month-names. Reads more naturally, makes it easier to avoid errors.

**Comment by symroe** [comment]
So I built it this way following GDS best practice from this page: https://designnotes.blog.gov.uk/2013/12/05/asking-for-a-date-of-birth/

(more [here](https://www.gov.uk/service-manual/design/dates) and [here](https://designpatterns.hackpad.com/Dates-vpx6XlVjIbE)).

But they are designed for _everyone_, where as I expect this form will most likely be used by just us, or a few quite advanced users.

I'd be happy to give it a go, if you think we don't fit in to the cases that the GDS research was focusing on?

**Comment by JoeMitchell** [comment]
Hmm, tricky. I'm just going on my own wishes, whereas they did some research, so happy to stick with general practice.
