### ISSUE TITLE
Store NUTS1 area for divisions and organisations

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#815]
A feature request from YNR that's easy to imagine being useful to other users is to be able to filter ballots by _some regional grouping_. 

It makes sense to use the NUTS1 groups, e.g the old `europarl` divisions for this. There are 9 English areas, and 3 more for Wales, Scotland and Northern Ireland.

Seems like a good approach would be to add a `nuts_area` column to `OrganisationDivision` and `Organisation`. This can be populated using the existing boundaries we have, e.g:

```python
regions = OrganisationDivision.objects.filter(division_type="EUR")
for region in regions:
    OrganisationDivision.objects.annotate(cent=Centroid("geography__geography")).filter(cent__within=region.geography.geography).update(nuts_area=region.slug)
```

(The actual code wouldn't be the slug, but we can use a lookup between slug and code).

This would then be exposed in the API for consumers to use.

**Comment by GeoWill** [comment]
Another way that would let us add a variety of regional groupings would be to use a jsonb column on `OrganisationDivision`. It could be called `tags` or `groups` or similar.
It would look like:

```json
{
    "nuts1": {"value": "foo", "label": "bar"},
    "historic_county": {"value": "foo", "label": "bar"}
}
```

This would get populated with a management command, so could be flexible about whether the geometries we're grouping by live in a file or the db. Given this'll be consumed by YNR we would need to pass back an issue when an expected tag was missing. 

--------------------------

Also a couple of possible issues with using centroid: 
- In case of islands the centroid might not fall within the grouping geom.
- If we're grouping by geometries that won't neatly contain divisions then we might want to base tagging on a threshold overlap - eg at least 50% contained by this geometry.

**Comment by pmk01** [comment]
As part of this it would also be good if we could filter by District, County, Unitary & Metropolitan District councils...

**Comment by GeoWill** [comment]
Tags for NUTS1 areas are in the DB and being pulled through to the API:
```json
[...,
{
    "election_id": "local.brentwood.hutton-central.2021-05-06",
    "tmp_election_id": null,
    "election_title": "Brentwood local election Hutton Central",
    "poll_open_date": "2021-05-06",
    "election_type": {...},
    "election_subtype": null,
    "organisation": {...},
    "group": "local.brentwood.2021-05-06",
    "group_type": null,
    "identifier_type": "ballot",
    "children": [],
    "elected_role": "Local Councillor",
    "seats_contested": 1,
    "division": {...},
    "voting_system": {...},
    "current": true,
    "explanation": null,
    "metadata": null,
    "deleted": false,
    "cancelled": false,
    "replaces": "local.brentwood.hutton-central.2020-05-07",
    "replaced_by": null,
    "tags": {
        "NUTS1": {
            "key": "UKH",
            "value": "East of England"
        }
    }
},
...]
```
Going to say we should punt Districts, Counties, and other groupings to other issues, since how we tackle them may vary - i.e. we might want to create a command that can tag areas based on other areas in our db.
