### ISSUE TITLE
accurately list authorities with directly elected mayors

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#88]
Tried to create an election ID for Mayor Hackney on 03/05/2018 but Hackney isn't listed as an available authority for a Mayoral election. There are also a variety of other areas missing. We should accurately list in the ID creator all areas which may have a mayoral election.
For example: http://www.londoncouncils.gov.uk/who-runs-london/london-elections/elected-mayors
also, I think Bristol has a directly elected Mayor and isn't listed, as another example.

Where can we source this from?

**Comment by symroe** [comment]
Not sure where we source it from, but we should add the orgs to the `orgs_with_mayors` list here:

https://github.com/DemocracyClub/EveryElection/blob/master/every_election/apps/organisations/importers.py#L159
