### ISSUE TITLE
Greater Manchester PCC

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/EveryElection#905]
"greater-manchester" should be added to the list of areas without PCCs. Police and fire are the responsibility of the CA.

**Comment by symroe** [comment]
This is done at the `Organisation` level:

https://elections.democracyclub.org.uk/organisations/police-area/greater-manchester/2012-11-15/ is the organisation that used to have elections, and the end date is set already. This means that we can't create elections with a poll date after 8 May 2017.
