### ISSUE TITLE
Election Types list needs updating

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/EveryElection#973]
https://elections.democracyclub.org.uk/election_types/
We have two EU elections here and Assembly for Wales needs changing. 

Similarly, 'organisations' needs a update to change NAW: https://elections.democracyclub.org.uk/organisations/

**Comment by GeoWill** [comment]
I don't think NAW should be removed/change, it still exists historically. We just have Senedd as a new type.

**Comment by GeoWill** [comment]
The double EU issue was caused by an extra entry in the ElectionType table.
There are two `ElectionType: European Parliament (UK) elections` one with `id=10` and one `id=12`. From the following I think it's safe to delete the one with `id=12` but would be good to get a thumbs up from @symroe.

```python
>>> eu_10 = ElectionType.objects.get(pk=10)
>>> eu_12 = ElectionType.objects.get(pk=12)
>>> collector_10 = NestedObjects(using=connection.cursor().db.alias)
>>> collector_10.collect([eu_10])
>>> collector_12 = NestedObjects(using=connection.cursor().db.alias)
>>> collector_10.nested()
[<ElectionType: European Parliament (UK) elections>, [<ElectedRole: Member of European Parliament (European Union Parliament (01 Nov 1993 onwards))>, [<Election: europarl.uk-eastern.2014-05-22>, [<ModerationHistory: ModerationHistory object (24340)>, <ModerationHistory: ModerationHistory object (24328)>], ... LotsMore ...]
>>> collector_12.collect([eu_12])
>>> collector_12.nested()
[<ElectionType: European Parliament (UK) elections>]
```

**Comment by symroe** [comment]
Hmm, I'm a little confused as to why `12` contains less information than `10`. I thought we made `eu` first and then moved to `europarl` later. Can you just make sure that we're not in a pickle somehow in using the wrong election type?

We want to keep `europarl` and not `eu`, so if `12` is `eu` then it's good to delete!

**Comment by GeoWill** [comment]
So locally I'm pretty sure `europarl` is `10` and `eu` is `12`. That does seem a bit confusing about how they got created though. I will check on prod, and make sure I delete whichever has `election_type` set to `eu`, so long as nothing else is depending on it - which I think I can use `NestedObjects` for. 

------------------------------------


Check for type/id:
```python
>>> eu_10 = ElectionType.objects.get(pk=10)
>>> eu_12 = ElectionType.objects.get(pk=12)
>>> eu_10.election_type
'europarl'
>>> eu_12.election_type
'eu'
>>> ElectionType.objects.get(election_type='eu').id
12
>>> ElectionType.objects.get(election_type='europarl').id
10
>>> 
```

**Comment by GeoWill** [comment]
Done.
